version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3005:3030'
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
      - mysql
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  mysql:
    container_name: mysql_inside_dc
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: 'testing' # TODO: Change this
      MYSQL_USER: 'root'
      MYSQL_PASS: ''
    ports:
      - "3306:3306"
